import 'package:youtube_player_flutter/youtube_player_flutter.dart';

class Videos {
  final String cartoonName;
  final String imagePath;
  final List<YoutubePlayerController> videosIDs;

  Videos({
    required this.cartoonName,
    required this.imagePath,
    required this.videosIDs,
  });
}

class VideosList {
  static List<Videos> videoCard = [
    Videos(
      cartoonName: 'Teen Titans Go!',
      imagePath: 'assets/image/cartoon/teen.jpg',
      videosIDs: [
        'd1s8eC5oRr0',
        'fTl7r-5h7gg',
        'qbdbuKSrS74',
        'zjq183_kLtw',
        's2VNrUKBatE',
        'JyFsXEqv6_Y',
        '84Jigcr26Q4',
        '3BBL4la_-CI',
        'aEZwD_D9I1U',
        'obIS4iZOMhc',
        'GiDdlsPn6dw',
        'nnXtrhy7gOw',
        'WHeCv1Q8Z_4',
        'J-F-0phdRF0',
        '9FwPa-WLWcY',
        'vr1GI8HqJXE',
        'oU3QMGQXlG0',
        'GQxqnDBFkCk',
        'NMONf2hG9tY',
        'Mh2Zcau7aGk',
        'oGspv9mHh6I',
        'vKVygunm60Q',
        'p9Ioo5NNb9s',
        'tSpVf4s-rVc',
        'CGBKI6fg5Z4',
        'OA9xKxQVqrs',
        '4OaiPv_MeyY',
        'Kfoq9ORhNPE',
        'KbfR5JJiORk',
        'k9YEY2WV8rk',
        '5WZ_MxhB634',
        'xQSg4gEWB9I',
        'MTbpypzHBzg',
        'LIbQhyRRALc',
        'pk0Ju3VCXK8',
        '9skx-pCSs_c',
        'Nb6IrkRfXZQ',
        'aby-OobHYnE',
        'R8PRojSgI2I',
        '33jzuiLtsc8',
        'XrdijasiVFM',
        'Yl_m2cVQe_Y',
        'HhVIBeOn2jM',
        'KivNRGE8G5I',
        '4djb1n3MqrI',
        'yMXPND4MaCo',
        'L4vILuEZUfE',
        'dwjYGeF6MRM',
        '69cH_t0BR4o',
        '1vNpa1SOTvk'
      ]
          .map<YoutubePlayerController>(
            (videoId) => YoutubePlayerController(
              initialVideoId: videoId,
              flags: const YoutubePlayerFlags(
                autoPlay: false,
              ),
            ),
          )
          .toList(),
    ),
    Videos(
        cartoonName: 'Tom&Jerry',
        imagePath: 'assets/image/cartoon/tom.jpg',
        videosIDs: [
          'PKAaEVdYFfA',
          'tIZAyTi1PZE',
          'Z6rFBDKxZWg',
          'Jg9mvKAnI4A',
          '6Ms4BMZtHk4',
          'qwLNyRVKy98',
          'Ftjt7KrNpFU',
          'Ki599jN3uqY',
          'Nso7F78DDvA',
          'vxqXHsAHNG8',
          'dB4tUSd375w',
          't-Nw9oz-U6M',
          'id7qgnqIZtg',
          'DvUadTYVzAs',
          'mNNPeK6xM0Q',
          '42sDEH4ocOY',
          'TlLNCH6GzNs',
          'DxNZHqVoTSA',
          '2bFLu-cZpIk',
          'hwMGDTDoNPA',
          'Hn3l_QpevHo',
          '1K5QIfQzdv0',
          'b_zcMT7C6ms',
          'NwM9ADZ6sdU',
          '6YC1B45fYfk',
          'tsaRPgQzGQ0',
          'IWc-hotGwcM',
          'EXbW7F7hKNA',
          'sZUPaNrYgK4',
          'ZjbJ3q_ZfVk',
          'q8byMnzAjC4',
          '5JDAF86rS6M',
          'mPeOaZIkwrw',
          '-tcuHxWsWNY',
          'p4mwYI1Pljs',
          '8IQif6bDO88',
          'nYAuyE2a0dA',
          'rhcjYIPgpt8',
          'sZRWLaBc3Ko',
          'ZSOiUL-y9uA',
          '_YMVQEpKW_k',
          'qHl8E24Eznw',
          'WFvKKB8tUZg',
          '5x4gj5OKo9I',
          '1QZxybUVrFs',
          'DatgcPn3oag',
          '3sMqNvZRnOc',
          'oMjq1W7i3Tc',
          'iwUsUWwcEtQ',
          'S7CHWXCDLBo'
        ]
            .map<YoutubePlayerController>(
              (videoId) => YoutubePlayerController(
                initialVideoId: videoId,
                flags: const YoutubePlayerFlags(
                  autoPlay: false,
                ),
              ),
            )
            .toList()),
    Videos(
        cartoonName: 'SpongeBob',
        imagePath: 'assets/image/cartoon/sponge.png',
        videosIDs: [
          'X0BE1i-5SrA',
          'f5-dtT9q1jo',
          'pE_4aUijJd4',
          '0mDw1RwGRe4',
          'MMivd32KWps',
          'akz7ZtZ-Ep8',
          'p-OoQNgxrlU',
          'z7UrxrCPxBs',
          'CUElNVuE7ME',
          '17x9ac9cXWU',
          'XzSx9Ei-8R8',
          'T7r9gOZv0ZQ',
          'xfgcLN9znaQ',
          'OxCiRMBKIFE',
          'ulj0loJwHMI',
          'GXdSxTCvub4',
          'Glf7Iz7UicI',
          'jYI8x7bL55w',
          'r1Zw39t2snQ',
          'QHiGu5IY-Uk',
          '-pQfiLO74sE',
          'kWqALkrcaN4',
          '-AwJq2up4Zs',
          'S6Ky8mmot-I',
          '5U_CEYEnZbM',
          'G8di8UmQIEw',
          '-y0Z_OfkLtI',
          'VHIaHHMcsjw',
          'QCBigyp8mMI',
          'Wtp0R3uaTJ8',
          'hD6Cg87nH_Y',
          'fytsaon_eOo',
          'g9oskrqREu0',
          'GgtMz6ZVFE0',
          'QW-LJseamD0',
          'xovQE_r8Fds',
          'nT8yPDOVxy0',
          'XOosEKi45Ls',
          'OaZKuQWg4EY',
          '6ZE8RL9jcuw',
          'VkXVvfMmOeU',
          '_CNAoSzDlVo',
          'gTTnNTw5sDw',
          'YsWeJP9UKTE',
          'v_voUsw9Pc4',
          'GsVQ4SAkE9s',
          'yNPLpk755D0',
          'nCE6Vbq40E4',
          'nCE6Vbq40E4',
          'nCE6Vbq40E4'
        ]
            .map<YoutubePlayerController>(
              (videoId) => YoutubePlayerController(
                initialVideoId: videoId,
                flags: const YoutubePlayerFlags(
                  autoPlay: false,
                ),
              ),
            )
            .toList()),
    Videos(
        cartoonName: 'The Jungle Book',
        imagePath: 'assets/image/cartoon/thejunglebook.jpeg',
        videosIDs: [
          'GSGGsJzPt-k',
          'odvVf3ch64E',
          'agHoNRTL_Ks',
          '9HYE0zyvNa0',
          'vumSKwmyMwA',
          'D1IpMgi_AdY',
          'tvbITfFc1JY',
          'IjVRuVi2OpE',
          'noE4RYrZlWE',
          '-oRcXfOhQBg',
          'kcV5qCOIFd4',
          'yWKOCigDGcg',
          'i2CRc_lvP9c',
          'EPHmjbnfI4w',
          '7amONlt3ico',
          '_vKqMeowndo',
          'CUEsO_wwRng',
          '5KoVEeMgo5Q',
          '_onV9cYu3Vc',
          'WaWzavX8ER4',
          'VifUIDCzFBI',
          'n-3iWFrWsCs',
          '-qjhhvJaUr0',
          'tVzUhU-4TRk',
          '4y0mCUpb1as',
          'FBZxIaaPysg',
          'RVQT6Yjxqek',
          '8VOlZ5rsUJU',
          'ZwhTF49ttCQ',
          'tE5SaR0PjpA',
          'oQnt3dvXgLg',
          'fMMeKJrkiAs',
          '8HgZohYHi_8',
          'mW-56LD_goo',
          'Qr0bTcNZfps',
          'vGWFVPMnXYM',
          'abX30uWTuPI',
          'YL_vMKfQMDw',
          'wj7qajFXHAY',
          'S9Ndnw-QIVs',
          '8uSy6PuMML8',
          'RPEihuRlYUU',
          'VlqktdS07OI',
          'CbjebsaBdec',
          'FfvNySrhOMo',
          'VVWXnhNxL1I',
          'Ne-QY4CxWc0',
          'dB0I88baOTw',
          'jYU_s5gh8Tg',
          '_rE-V5Wb8nQ',
          'A-DWRBh7SEI',
          'OgN44L48eeM',
          'EWL3E9Lu1kg'
        ]
            .map<YoutubePlayerController>(
              (videoId) => YoutubePlayerController(
                initialVideoId: videoId,
                flags: const YoutubePlayerFlags(
                  autoPlay: false,
                ),
              ),
            )
            .toList()),

    // Videos(
    //     cartoonName: 'Tom&Jerry',
    //     imagePath: 'assets/image/cartoon/tom.jpg',
    //     videosIDs: fetchVideoIds('PLJYf0JdTApCqAbZImkQagXEuByh-b_7To')
    // ),
  ];
}
